Repository atlp-rwanda/knights-ecomm-be, pull requests merged in 2024-04, with the labels that each got.

#21 chore: swagger API documentation
  package.json
  src/configs/swagger.ts
  src/docs/index.yml
  src/index.ts
  src/routes/index.ts
  src/startups/docs.ts
  src/startups/getSwaggerServer.ts
Labels: Ready for reviews

#24 ch: Updated README file
  README.md
Labels: Ready for reviews

#26 Added a global error handler middleware
  src/index.ts
  src/middlewares/errorHandler.ts
Labels: Ready for reviews

#34 Ch config logging
  .eslintrc.js
  .gitignore
  .prettierrc
  README.md
  jest.config.ts
  package.json
  src/configs/index.ts
  src/configs/swagger.ts
  src/controllers/index.ts
  src/docs/index.yml
  src/index.ts
  src/middlewares/errorHandler.ts
  src/middlewares/index.ts
  src/routes/index.ts
  src/services/index.ts
  src/startups/docs.ts
  src/startups/getSwaggerServer.ts
  src/utils/index.ts
  src/utils/logger.ts
  src/utils/response.utils.ts
  tsconfig.json
Labels: chore, backend

#37 Chore: Database set up PR. #27
  .DS_Store
  package.json
  src/.DS_Store
  src/configs/db_config.ts
  src/index.ts
  src/startups/dbConnection.ts
Labels: backend, Ready for reviews
