Repository atlp-rwanda/knights-ecomm-be, pull requests merged in 2024-06, with the labels that each got.

#107 Implement buyer able to leave feedback on products
  src/__test__/cart.test.ts
  src/__test__/test-assets/DatabaseCleanup.ts
  src/controllers/feedbackController.ts
  src/entities/Feedback.ts
  src/entities/Order.ts
  src/entities/Product.ts
  src/entities/User.ts
  src/routes/ProductRoutes.ts
  src/routes/feedbackRoutes.ts
  src/routes/index.ts
  src/services/feedbackServices/adminDeleteFeedback.ts
  src/services/feedbackServices/createFeedback.ts
  src/services/feedbackServices/deleteFeedback.ts
  src/services/feedbackServices/updateFeedback.ts
  src/services/orderServices/createOrder.ts
  src/services/orderServices/getOrderTransactionHistory.ts
  src/services/orderServices/updateOrderService.ts
  src/services/productServices/getRecommendedProductsService.ts
  src/services/productServices/listAllProductsService.ts
  src/services/productServices/readProduct.ts
  src/services/productServices/viewSingleProduct.ts
Labels: backend, Ready for reviews

#110 Feat-Notification-Management
  src/__test__/cart.test.ts
  src/__test__/notification.test.ts
  src/__test__/test-assets/DatabaseCleanup.ts
  src/controllers/notificationControllers.ts
  src/controllers/orderController.ts
  src/docs/notifications.yml
  src/docs/orderDocs.yml
  src/entities/Notification.ts
  src/entities/NotificationItem.ts
  src/entities/VendorOrderItem.ts
  src/routes/NoficationRoutes.ts
  src/routes/ProductRoutes.ts
  src/routes/index.ts
  src/services/adminOrderServices/updateOrder.ts
  src/services/couponServices/buyerApplyCoupon.ts
  src/services/couponServices/createCouponService.ts
  src/services/feedbackServices/createFeedback.ts
  src/services/index.ts
  src/services/notificationServices/deleteNotification.ts
  src/services/notificationServices/getNotifications.ts
  src/services/notificationServices/updateNotification.ts
  src/services/orderServices/createOrder.ts
  src/services/orderServices/getOrderService.ts
  src/services/orderServices/updateOrderService.ts
  src/services/userServices/userDisableTwoFactorAuth.ts
  src/services/userServices/userEnableTwoFactorAuth.ts
  src/utils/getNotifications.ts
  src/utils/sendNotification.ts
Labels: Ready for reviews, Highest priority, Notification

#116 Ft: Increase test coverage PR
  .github/workflows/ci.yml
  .gitignore
  \
  jest.config.ts
  model.nlp
  package.json
  src/__test__/auth.test.ts
  src/__test__/cart.test.ts
  src/__test__/coupon.test.ts
  src/__test__/getProduct.test.ts
  src/__test__/index.test.ts
  src/__test__/index.utils.test.ts
  src/__test__/isAllowed.test.ts
  src/__test__/logger.test.ts
  src/__test__/logout.test.ts
  src/__test__/product.entities.test.ts
  src/__test__/productStatus.test.ts
  src/__test__/roleCheck.test.ts
  src/__test__/route.test.ts
  src/__test__/searchProduct.test.ts
  src/__test__/user.entity.test.ts
  src/__test__/userServices.test.ts
  src/__test__/userStatus.test.ts
  src/__test__/vendorProduct.test.ts
  src/__test__/wishList.test.ts
  src/controllers/productController.ts
  src/entities/User.ts
  src/helper/couponValidator.ts
  src/middlewares/isAllowed.ts
  src/routes/ProductRoutes.ts
  src/routes/UserRoutes.ts
  src/routes/index.ts
  src/services/adminOrderServices/updateOrder.ts
  src/services/cartServices/clearCart.ts
  src/services/cartServices/readCart.ts
  src/services/cartServices/removeProductInCart.ts
  src/services/couponServices/accessAllCoupon.ts
  src/services/couponServices/createCouponService.ts
  src/services/couponServices/deleteCoupon.ts
  src/services/couponServices/readCoupon.ts
  src/services/couponServices/updateService.ts
  src/services/feedbackServices/adminDeleteFeedback.ts
  src/services/notificationServices/updateNotification.ts
  src/services/orderServices/getOrderService.ts
  src/services/orderServices/updateOrderService.ts
  src/services/productServices/createProduct.ts
  src/services/productServices/listAllProductsService.ts
  src/services/productServices/productStatus.ts
  src/services/productServices/readProduct.ts
  src/services/productServices/searchProduct.ts
  src/services/productServices/viewSingleProduct.ts
  src/services/userServices/sendResetPasswordLinkService.ts
  src/services/userServices/userPasswordResetService.ts
  src/services/userServices/userProfileUpdateServices.ts
  src/services/userServices/userValidationService.ts
  src/services/wishListServices/addProduct.ts
  src/services/wishListServices/clearAll.ts
  src/services/wishListServices/getProducts.ts
  src/services/wishListServices/removeProducts.ts
  tsconfig.json
Labels: Ready for reviews, Highest priority, fixing jobs

#117 Bug remove invalid path file
  \
Labels: bug, backend
