Repository atlp-rwanda/knights-ecomm-be, pull requests merged in 2024-05, with the labels that each got.

#52 Implemented user registration feature with input validation, password hashing, and database integration
  .gitignore
  migrations/1714595134552-UserMigration.ts
  package.json
  src/__test__/route.test.ts
  src/controllers/authController.ts
  src/controllers/index.ts
  src/entities/User.ts
  src/index.ts
  src/middlewares/errorHandler.ts
  src/routes/UserRoutes.ts
  src/routes/index.ts
  tsconfig.json
Labels: Ready for reviews, Highest priority

#59 Add User Verification Route and Email Notification
  .github/workflows/ci.yml
  package.json
  src/__test__/route.test.ts
  src/controllers/authController.ts
  src/controllers/index.ts
  src/routes/UserRoutes.ts
  src/services/index.ts
  src/services/userServices/userRegistrationService.ts
  src/services/userServices/userValidationService.ts
  src/utils/sendMail.ts
Labels: Ready for reviews, Highest priority

#60 Feat: Two Factor Authentication(2FA)
  .env.example
  package.json
  src/__test__/route.test.ts
  src/__test__/userServices.test.ts
  src/controllers/authController.ts
  src/docs/authDocs.yml
  src/docs/swaggerDark.css
  src/entities/User.ts
  src/helper/emailTemplates.ts
  src/routes/UserRoutes.ts
  src/services/index.ts
  src/services/userServices/userDisableTwoFactorAuth.ts
  src/services/userServices/userEnableTwoFactorAuth.ts
  src/services/userServices/userIsOTPValid.ts
  src/services/userServices/userLoginService.ts
  src/services/userServices/userRegistrationService.ts
  src/services/userServices/userResendOTP.ts
  src/services/userServices/userSendOTPEmail.ts
  src/services/userServices/userSendOTPMessage.ts
  src/services/userServices/userStartTwoFactorAuthProcess.ts
  src/services/userServices/userValidateOTP.ts
  src/services/userServices/userValidationService.ts
  src/startups/docs.ts
Labels: backend, Ready for reviews, Highest priority

#61 feat(rbac): implement role-based access control
  package.json
  src/__test__/roleCheck.test.ts
  src/__test__/userServices.test.ts
  src/controllers/index.ts
  src/entities/User.ts
  src/middlewares/index.ts
  src/middlewares/roleCheck.ts
  src/routes/index.ts
  src/utils/roles.ts
  src/utils/sendMail.ts
Labels: backend, Ready for reviews

#54 adding reset password feature
  .env.example
  src/__test__/route.test.ts
  src/__test__/userServices.test.ts
  src/controllers/authController.ts
  src/controllers/index.ts
  src/middlewares/index.ts
  src/routes/UserRoutes.ts
  src/services/index.ts
  src/services/userServices/sendResetPasswordLinkService.ts
  src/services/userServices/userPasswordResetService.ts
Labels: backend, Ready for reviews, Highest priority

#65 feat-implement-user-status-update
  .github/workflows/ci.yml
  package.json
  src/__test__/isAllowed.test.ts
  src/__test__/route.test.ts
  src/__test__/userStatus.test.ts
  src/controllers/authController.ts
  src/controllers/index.ts
  src/controllers/manageStatusController.ts
  src/helper/verify.ts
  src/index.ts
  src/middlewares/isAllowed.ts
  src/middlewares/isValid.ts
  src/routes/UserRoutes.ts
  src/services/updateUserStatus/activateUserService.ts
  src/services/updateUserStatus/deactivateUserService.ts
  src/utils/sendStatusMail.ts
Labels: backend, Ready for reviews

#67 ft: implement user logout feature
  src/__test__/logout.test.ts
  src/__test__/route.test.ts
  src/__test__/userServices.test.ts
  src/__test__/userStatus.test.ts
  src/controllers/authController.ts
  src/helper/verify.ts
  src/index.ts
  src/middlewares/index.ts
  src/middlewares/isValid.ts
  src/routes/UserRoutes.ts
  src/services/index.ts
  src/services/userServices/logoutServices.ts
  src/services/userServices/userLoginService.ts
  src/services/userServices/userPasswordResetService.ts
  src/services/userServices/userResendOTP.ts
  src/services/userServices/userSendOTPEmail.ts
  src/utils/sendMail.ts
Labels: Ready for reviews

#64 Feat: Implement user profile update feature
  jest.config.ts
  src/__test__/isAllowed.test.ts
  src/__test__/logout.test.ts
  src/__test__/roleCheck.test.ts
  src/__test__/route.test.ts
  src/__test__/userServices.test.ts
  src/__test__/userStatus.test.ts
  src/controllers/authController.ts
  src/entities/User.ts
  src/routes/UserRoutes.ts
  src/services/index.ts
  src/services/userServices/userProfileUpdateServices.ts
  src/utils/sendStatusMail.ts
Labels: Ready for reviews

#74 #48 Vendor product management (CRUD)
  .env.example
  .github/workflows/ci.yml
  README.md
  package.json
  src/@types/index.d.ts
  src/__test__/isAllowed.test.ts
  src/__test__/roleCheck.test.ts
  src/__test__/route.test.ts
  src/__test__/test-assets/photo1.png
  src/__test__/test-assets/photo2.webp
  src/__test__/userStatus.test.ts
  src/__test__/vendorProduct.test.ts
  src/controllers/authController.ts
  src/controllers/index.ts
  src/controllers/productController.ts
  src/docs/authDocs.yml
  src/docs/vendorProduct.yml
  src/entities/Category.ts
  src/entities/Product.ts
  src/entities/User.ts
  src/helper/productValidator.ts
  src/lib/types.ts
  src/middlewares/isAllowed.ts
  src/middlewares/multer.ts
  src/middlewares/verifyToken.ts
  src/routes/ProductRoutes.ts
  src/routes/UserRoutes.ts
  src/routes/index.ts
  src/services/index.ts
  src/services/productServices/createProduct.ts
  src/services/productServices/deleteProduct.ts
  src/services/productServices/readProduct.ts
  src/services/productServices/removeProductImage.ts
  src/services/productServices/updateProduct.ts
  src/services/updateUserStatus/activateUserService.ts
  src/services/updateUserStatus/deactivateUserService.ts
  src/services/userServices/sendResetPasswordLinkService.ts
  src/services/userServices/userProfileUpdateServices.ts
  src/startups/getSwaggerServer.ts
  src/utils/cloudinary.ts
  src/utils/response.utils.ts
  src/utils/sendStatusMail.ts
  tsconfig.json
Labels: Ready for reviews, Highest priority

#81 feat: check product availablity status update PR
  src/__test__/productStatus.test.ts
  src/__test__/vendorProduct.test.ts
  src/controllers/productController.ts
  src/routes/ProductRoutes.ts
  src/services/index.ts
  src/services/productServices/productStatus.ts
  tsconfig.json
Labels: Ready for reviews, Highest priority

#80 removing console and sensitive data in reponse
  src/__test__/productStatus.test.ts
  src/services/productServices/getRecommendedProductsService.ts
Labels: backend

#85 Ft-implment-wish list-functionalites
  src/__test__/errorHandler.test.ts
  src/__test__/wishList.test.ts
  src/controllers/wishListController.ts
  src/entities/wishList.ts
  src/middlewares/errorHandler.ts
  src/routes/index.ts
  src/routes/wishListRoute.ts
  src/services/index.ts
  src/services/wishListServices/addProduct.ts
  src/services/wishListServices/clearAll.ts
  src/services/wishListServices/getProducts.ts
  src/services/wishListServices/removeProducts.ts
Labels: backend, Ready for reviews, Highest priority

#86 Implementation of view a Single Product Function
  src/__test__/getProduct.test.ts
  src/controllers/productController.ts
  src/routes/ProductRoutes.ts
  src/services/index.ts
  src/services/productServices/viewSingleProduct.ts
Labels: backend, Ready for reviews

#83 Implement buyer able to list all products
  src/__test__/vendorProduct.test.ts
  src/controllers/productController.ts
  src/routes/ProductRoutes.ts
  src/services/index.ts
  src/services/productServices/listAllProductsService.ts
Labels: backend, Ready for reviews

#84 google authentication
  .github/workflows/ci.yml
  package.json
  src/__test__/oauth.test.ts
  src/index.ts
  src/routes/ProductRoutes.ts
  src/routes/UserRoutes.ts
  src/routes/wishListRoute.ts
  src/utils/auth.ts
Labels: Ready for reviews, Highest priority

#87 Ft product search
  src/__test__/productStatus.test.ts
  src/controllers/productController.ts
  src/entities/Product.ts
  src/routes/ProductRoutes.ts
  src/services/index.ts
  src/services/productServices/createProduct.ts
  src/services/productServices/searchProduct.ts
Labels: Ready for reviews, Highest priority

#97 #88 Guest/Buyer Cart management
  src/__test__/cart.test.test.ts
  src/controllers/cartController.ts
  src/docs/cartDocs.yml
  src/entities/Cart.ts
  src/entities/CartItem.ts
  src/entities/Product.ts
  src/entities/User.ts
  src/helper/cartItemValidator.ts
  src/middlewares/optionalAuthorization.ts
  src/routes/CartRoutes.ts
  src/routes/index.ts
  src/services/cartServices/clearCart.ts
  src/services/cartServices/createCart.ts
  src/services/cartServices/readCart.ts
  src/services/cartServices/removeProductInCart.ts
  src/services/index.ts
  src/services/productServices/createProduct.ts
Labels: backend, Ready for reviews, Highest priority, cart

#95 This PR is adding discount coupon feature to vendor
  src/__test__/cart.test.test.ts
  src/__test__/coupon.test.ts
  src/__test__/getProduct.test.ts
  src/__test__/userServices.test.ts
  src/__test__/vendorProduct.test.ts
  src/__test__/wishList.test.ts
  src/controllers/couponController.ts
  src/docs/couponDocs.yml
  src/entities/Product.ts
  src/entities/coupon.ts
  src/helper/couponValidator.ts
  src/routes/couponRoutes.ts
  src/routes/index.ts
  src/services/couponServices/accessAllCoupon.ts
  src/services/couponServices/createCouponService.ts
  src/services/couponServices/deleteCoupon.ts
  src/services/couponServices/readCoupon.ts
  src/services/couponServices/updateService.ts
Labels: Ready for reviews, Highest priority, coupon

#94 Buyer order tracking
  src/__test__/cart.test.ts
  src/__test__/coupon.test.ts
  src/__test__/getProduct.test.ts
  src/__test__/isAllowed.test.ts
  src/__test__/logout.test.ts
  src/__test__/oauth.test.ts
  src/__test__/productStatus.test.ts
  src/__test__/roleCheck.test.ts
  src/__test__/route.test.ts
  src/__test__/test-assets/DatabaseCleanup.ts
  src/__test__/userServices.test.ts
  src/__test__/userStatus.test.ts
  src/__test__/vendorProduct.test.ts
  src/__test__/wishList.test.ts
  src/controllers/index.ts
  src/controllers/orderController.ts
  src/docs/orderDocs.yml
  src/entities/Order.ts
  src/entities/OrderItem.ts
  src/entities/Product.ts
  src/entities/User.ts
  src/entities/transaction.ts
  src/routes/ProductRoutes.ts
  src/services/cartServices/createCart.ts
  src/services/orderServices/createOrder.ts
  src/services/orderServices/getOrderService.ts
  src/services/orderServices/getOrderTransactionHistory.ts
  src/services/orderServices/updateOrderService.ts
  src/utils/index.ts
  src/utils/response.utils.ts
  src/utils/sendOrderMail.ts
  src/utils/sendOrderMailUpdated.ts
Labels: backend, Ready for reviews, product

#100 Feat-Buyer-coupon-discount-management
  src/__test__/coupon.test.ts
  src/controllers/couponController.ts
  src/docs/couponDocs.yml
  src/docs/wishListDocs.yml
  src/entities/coupon.ts
  src/routes/couponRoutes.ts
  src/services/couponServices/buyerApplyCoupon.ts
Labels: backend, Ready for reviews, Highest priority, coupon

#103 Stripe Payment system Integration
  .github/workflows/ci.yml
  package.json
  src/__test__/getProduct.test.ts
  src/controllers/productController.ts
  src/entities/User.ts
  src/entities/transaction.ts
  src/routes/ProductRoutes.ts
  src/services/index.ts
  src/services/orderServices/createOrder.ts
  src/services/orderServices/updateOrderService.ts
  src/services/productServices/payment.ts
Labels: backend, Ready for reviews, Highest priority, Payments

#108 implement Docker for project
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
Labels: backend, Ready for reviews, Highest priority
